# Generated by Django 3.1.2 on 2020-11-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xCommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='create_at',
        ),
    ]
