# Generated by Django 3.1.2 on 2020-11-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xCommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='counrty',
            new_name='country',
        ),
    ]
