# Generated by Django 3.1.2 on 2020-11-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xCommerce', '0002_auto_20201102_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
