# Generated by Django 3.1.2 on 2020-11-02 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xCommerce', '0002_remove_customer_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='extra',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_default',
        ),
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(default='test', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default='test', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default='000000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default='123', max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='counrty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xCommerce.country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xCommerce.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
