# Generated by Django 3.1.2 on 2020-11-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xCommerce', '0003_auto_20201103_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(max_length=191),
        ),
    ]
