# Generated by Django 3.1.2 on 2020-11-03 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xCommerce', '0004_auto_20201103_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
