# Generated by Django 3.1.2 on 2020-11-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xCommerce', '0005_auto_20201102_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='subtotal',
            new_name='line_item_total',
        ),
    ]
