# Generated by Django 3.1.2 on 2020-11-02 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xCommerce', '0006_auto_20201102_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='counrty',
            new_name='country',
        ),
    ]
